# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply two matrices using RcppArmadillo
#'
#' @param A B two matrices
#' @export
armaMatMult <- function(A, B) {
    .Call('_VN_armaMatMult', PACKAGE = 'VN', A, B)
}

#' Transpose of a matrix using RcppArmadillo
#'
#' @param A matrix
#' @export
armaMatT <- function(A) {
    .Call('_VN_armaMatT', PACKAGE = 'VN', A)
}

#' Multiply two matrices using RcppEigen
#'
#' @param A B two matrices
#' @export
eigenMatMult <- function(A, B) {
    .Call('_VN_eigenMatMult', PACKAGE = 'VN', A, B)
}

#' Transpose of a matrix using RcppEigen
#'
#' @param A matrix
#' @export
eigenMatT <- function(A) {
    .Call('_VN_eigenMatT', PACKAGE = 'VN', A)
}

#' Multiply two matrices using RcppEigen::Map
#'
#' @param A B two matrices
#' @export
eigenMapMatMult <- function(A, B) {
    .Call('_VN_eigenMapMatMult', PACKAGE = 'VN', A, B)
}

#' Transpose matrix using RcppEigen::Map
#'
#' @param A matrix
#' @export
eigenMapMatT <- function(A) {
    .Call('_VN_eigenMapMatT', PACKAGE = 'VN', A)
}

